version: 1.0.0.{build}
install:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -outfile dotnet-install.ps1
  - ps: .\dotnet-install.ps1 -Version 2.1.300 -InstallDir $env:ProgramFiles/dotnet
branches:
  only:
    - master
    - appveyor
    - /^feature\/.*/
build_script:
  - ps: .\build.ps1 -IsOfficialBuild
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
artifacts:
  - path: 'artifacts\*.nupkg'
    name: Packages
    type: NuGetPackages
deploy:
  - provider: NuGet
    name: myget
    artifact: Packages
    server: https://www.myget.org/F/jerriep/api/v2/package
    symbol_server: https://www.myget.org/F/jerriep/api/v2/package
    api_key:
      secure: Nadp4it+3cE5F7eSCtkq6k222r0ykbt0ZeCBmbznUSmUqjFIDnyuUaVZUn66PV3A