#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

pull_requests:
  do_not_increment_build_number: true

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017 Preview

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- ps: .\build.ps1

test: off
deploy: off

artifacts:
- path: '**\*.nupkg' # find all NuGet packages recursively